name: networkcommons_test
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - bioconductor-deseq2=1.42.0
  - graphviz=2.50.0
  - pip=24.0
  - python=3.10.14
  - python-graphviz=0.20.3
  - r-base=4.3.1
  - setuptools=69.5.1
  - pip:
      - cvxpy==1.4.3
      - decoupler==1.6.0
      - flake8==7.0.0
      - gurobipy==11.0.1      
      - networkx==3.3
      - omnipath==1.0.8
      - pathos==0.3.2
      - picos==2.4.17
      - pyocclient==0.6
      - pytest==8.2.0
      - pytest-cov==5.0.0
      - requests==2.31.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - scipy==1.11.4
      - urllib3==2.2.1
