name: build

on:
  push:
    branches: [ dev ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev
        python -m pip install --upgrade pip
        sudo apt-get install -y r-base
        sudo apt-get install graphviz libgraphviz-dev pkg-config
        pip install pytest-cov flake8 decoupler omnipath requests rpy2 pathos
        pip install git+https://github.com/saezlab/corneto.git@dev networkx pygraphviz picos .
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test and add coverage
      run: |
        pytest --cov --disable-warnings networkcommons